### ISSUE TITLE
Support selectOne and support java8 Optional

### ISSUE THREAD

**Issue by jimyip** [icuter/jsql#3]
1. The results we get by querying are collections, sometimes we just want to get a record, so we want to support querying a record not a list.
2. When querying data, we are not sure whether the result returned is null. We need the query result to return the optional object.

**Comment by ty-Isaac** [comment]
you could  use query sql like select ..... limit 1 or add more conditions.

**Comment by edwardleejan** [comment]
> 1. The results we get by querying are collections, sometimes we just want to get a record, so we want to support querying a record not a list.
> 2. When querying data, we are not sure whether the result returned is null. We need the query result to return the optional object.

Do you mean `selectOne` like querying with ID condition and return `Optional<T>` in case `selectOne` return `null`? Alternatively, you could query with ID condition like `where().eq("id", "****")` and return the result like `list.isEmpty ? DefaultObject : list.get(0)`.
