### ISSUE TITLE
Connection pool can be selected manually

### ISSUE THREAD

**Issue by jimyip** [icuter/jsql#4]
1. when we use the lib to get a connection,we want to use other datasources like c3p0, druid etc. however, we can't choose others.

**Comment by edwardleejan** [comment]
Sorry for closing mistake

Hi Jim

The feature that compatible with others' connection pool framework sounds a good idea, but I recommend you to try using JSQL connection pool which is pretty efficient. 

Anyway, I have added to my TO-DO list and willing to implement it.
